### ISSUE TITLE
expandjs 1.X

### ISSUE THREAD

**Issue by danielsogl** [Pupix/lol-riot-api#10]
Is it possible to update to the latest expandjs release? I'm not really in that library so maybe you can do that for me.

I only have problems with the removed merge and forEach method.

**Comment by Pupix** [comment]
Updated.

**Comment by danielsogl** [comment]
Can you fix the 

```
 // Dynamic API routes with cache
XP.forEach(routes, function(func, route) 
```

part too? Thank you

**Comment by danielsogl** [comment]
And in the module repo, the XP.includes function is not valid anymore.

**Comment by Pupix** [comment]
Oops, sorry about that! Everything should be fine now,
